/**
 * Golden cases generated by running the real C# MqttAdapter (see ../../../parity/).
 * If MqttAdapter.cs changes, regenerate the fixture and this test shows the drift.
 */
import { describe, expect, it } from 'vitest'
import fixture from '../__fixtures__/mqttadapter-parity.json'
import { parseMqttMessage } from '../parsePayload'

interface Case {
  name: string
  topic: string
  payloadBase64: string
  expected:
    | { kind: 'sample'; tag: string; value: number | string; negZero: boolean; quality: string | null }
    | { kind: 'rejected' }
    | { kind: 'error'; exception: string }
}

const decodeB64 = (b64: string) => Uint8Array.from(atob(b64), (c) => c.charCodeAt(0))
const cases = fixture as Case[]

describe('parity with C# MqttAdapter (dotnet-generated fixture)', () => {
  it('has a meaningful number of cases', () => {
    expect(cases.length).toBeGreaterThan(50)
  })

  it.each(cases.map((c) => [c.name, c] as const))('%s', (_name, c) => {
    const receivedAt = new Date(0)
    const r = parseMqttMessage({ topic: c.topic, payload: decodeB64(c.payloadBase64), receivedAt })
    expect(r.kind).toBe(c.expected.kind)
    if (c.expected.kind !== 'sample' || r.kind !== 'sample') return

    expect(r.sample.tag).toBe(c.expected.tag)
    expect(r.sample.quality).toBe(c.expected.quality)
    expect(r.sample.timestamp).toBe(receivedAt)
    const expectedValue = typeof c.expected.value === 'string' ? Number(c.expected.value) : c.expected.value
    expect(Object.is(r.sample.value, c.expected.negZero ? -0 : expectedValue)).toBe(true)
  })
})
